SalesApp/Models/SprintViewModel.cs
namespace SalesApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    using Contract.Infrastructure.DataContracts.Sprint;

    public class SprintViewModel
    {
        public int SprintId { get; set; }

        public string Name { get; set; }

        public DateTime? From { get; set; }

        public  DateTime? To { get; set; }

        public List<TaskViewModel> TaskModels { get; set; }
    }
}

SalesApp/Controllers/SprintController.cs
using System;
using System.Collections.Generic;
using System.Linq;

using Microsoft.AspNetCore.Mvc;

namespace SalesApp.Controllers
{
    using AutoMapper;

    using Contract.Infrastructure.DataContracts.Sprint;
    using Contract.Infrastructure.Services;

    using SalesApp.Models;

    public class SprintController : Controller
    {
        private IDbWebService<SprintModel> service;
        private IMapper mapper;

        private IDbWebService<TechnologyFilterModel> techFilterService;
        private IDbWebService<TechnologyModel> techService;

        public SprintController(IDbWebService<SprintModel> service, IDbWebService<TechnologyFilterModel> techFilterService, IDbWebService<TechnologyModel> techService, IMapper mapper)
        {
            this.techService = techService;
            this.techFilterService = techFilterService;

            this.service = service;
            this.mapper = mapper;
        }

        // GET: Sprint
        public ActionResult Index()
        {
            this.ViewData["Title"] = "Sprints";

            var list = this.mapper.Map<List<SprintViewModel>>(this.service.GetAll());

            return this.View(list);
        }

        // GET: Sprint/Details/5
        public ActionResult Details(int id)
        {
            var item = this.service.GetById(id, model => model.TaskModels);

            this.ViewData["Title"] = item.Name + " - Sprint";

            var sprint = this.mapper.Map<SprintViewModel>(item);
            for (var i = 0; i < sprint.TaskModels.Count; i++)
            {
                sprint.TaskModels[i].SprintModel =
                    this.mapper.Map<SprintViewModel>(this.service.GetById(sprint.SprintId));

                sprint.TaskModels[i].TechnologyFilterViewModels = this.mapper.Map<List<TechnologyFilterViewModel>>(
                    this.techFilterService.Get(model => model.TaskId == sprint.TaskModels[i].TaskId));

                sprint.TaskModels[i].TechnologyViewModels = this.mapper.Map<List<TechnologyViewModel>>(
                    this.techService.Get(
                        model => sprint.TaskModels[i]
                            .TechnologyFilterViewModels.Any(
                                viewModel => model.TechnologyId == viewModel.TechnologyId)));
            }

            return this.View(sprint);
        }

        // GET: Sprint/Create
        public ActionResult Create()
        {
            this.ViewData["Title"] = "Create new sprint";

            var model = new CreateEditSprintViewModel();
            model.From = DateTime.Now.ToString("dd/MM/yyyy");
            model.To = DateTime.Now.ToString("dd/MM/yyyy");

            return this.PartialView("~/Views/Sprint/Create.cshtml", model);
        }

        // POST: Sprint/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CreateEditSprintViewModel model)
        {
            var response = new SprintResponse();

            if (this.ModelState.IsValid)
            {
                var item = this.mapper.Map<SprintModel>(model);
                if (this.service.Create(item))
                {
                    response.IsSuccess = true;
                    response.Title = "Success!";
                    response.Message = "Sprint created successful";
                    response.Model = this.mapper.Map<SprintViewModel>(item);
                }
                else
                {
                    response.IsSuccess = false;
                    response.Title = "Error!";
                    response.Message = "Something wrong, check log";
                }
            }
            else
            {
                response.IsSuccess = false;
                response.Title = "Error!";
                response.Message = string.Join("<br/>", this.ModelState.Keys.SelectMany(key => this.ModelState[key].Errors.Select(x => x.ErrorMessage)));
            }

            return this.Json(response);
        }

        // GET: Sprint/Edit/5
        public ActionResult Edit(int id)
        {
            this.ViewData["Title"] = "Edit sprint";

            var item = this.service.GetById(id);

            return this.PartialView("~/Views/Sprint/Edit.cshtml", this.mapper.Map<CreateEditSprintViewModel>(item));
        }

        // POST: Sprint/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(CreateEditSprintViewModel model)
        {
            var response = new SprintResponse();

            if (this.ModelState.IsValid)
            {
                var item = this.mapper.Map<SprintModel>(model);
                if (this.service.Update(item))
                {
                    response.IsSuccess = true;
                    response.Title = "Success!";
                    response.Message = "Sprint edit successful";
                    response.Model = this.mapper.Map<SprintViewModel>(item);
                }
                else
                {
                    response.Title = "Error!";
                    response.IsSuccess = false;
                    response.Message = "Something wrong, check log";
                }
            }
            else
            {
                response.Title = "Error!";
                response.IsSuccess = false;
                response.Message = string.Join("<br/>", this.ModelState.Keys.SelectMany(key => this.ModelState[key].Errors.Select(x => x.ErrorMessage)));
            }

            return this.Json(response);
        }

        // GET: Sprint/Delete/5
        [HttpGet]
        public ActionResult Delete(int id)
        {
            this.ViewData["Title"] = "Delete sprint";

            var item = this.service.GetById(id);

            return this.PartialView("~/Views/Sprint/Delete.cshtml", this.mapper.Map<CreateEditSprintViewModel>(item));
        }

        // POST: Sprint/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(CreateEditSprintViewModel model)
        {
            var response = new SprintResponse();

            var item = this.mapper.Map<SprintModel>(model);
            if (this.service.Delete(item.SprintId))
            {
                response.IsSuccess = true;
                response.Title = "Success!";
                response.Message = "Sprint delete successful";
                response.Model = this.mapper.Map<SprintViewModel>(item);
            }
            else
            {
                response.Title = "Error!";
                response.IsSuccess = false;
                response.Message = "Something wrong, check log";
            }

            return this.Json(response);
        }
    }
}

SalesApp/Views/Sprint/Create.cshtml
@using SalesApp.Models
@model SalesApp.Models.CreateEditSprintViewModel

<div class="row">
    <div class="col-sm-12 b-r">
        <h3 class="m-t-none m-b">@ViewData["Title"]</h3>

        <form asp-controller="Sprint" asp-action="Create" data-ajax-begin="onBegin" data-ajax-complete="onComplete" data-ajax-failure="onFailure" data-ajax="true" data-ajax-success="onSuccessCreate" data-ajax-method="POST" id="modalSubmit" class="form-horizontal">
            @Html.Partial("Partial/_CreateEditSprintPartial", Model)
        </form>

    </div>
</div>

@{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }

<environment names="Development">
    <script src="~/lib/bootstrap-datepicker/dist/js/bootstrap-datepicker.js" asp-append-version="true"></script>
</environment>
<environment names="Staging,Production">
    <script src="~/lib/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js"></script>
</environment>

<script>
    $('#dateRange .input-daterange').datepicker({
        keyboardNavigation: false,
        forceParse: false,
        autoclose: true,
        format: "dd/mm/yyyy"
    });
</script>

SalesApp/Views/Sprint/Delete.cshtml
@using SalesApp.Models
@model SalesApp.Models.CreateEditSprintViewModel

<div class="row">
    <div class="col-sm-12 b-r">
        <h3 class="m-t-none m-b">@ViewData["Title"]</h3>

        <form asp-controller="Sprint" asp-action="Delete" data-ajax-begin="onBegin" data-ajax-complete="onComplete" data-ajax-failure="onFailure" data-ajax="true" data-ajax-success="onSuccessDelete" data-ajax-method="POST" id="modalSubmit" class="form-horizontal">
            <p>Are you sure?</p>
            @Html.HiddenFor(m => m.SprintId)
            @Html.HiddenFor(m => m.Name)
            @Html.HiddenFor(m => m.From)
            @Html.HiddenFor(m => m.To)
            <button type="button" class="btn btn-white" data-dismiss="modal">Close</button>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>

    </div>
</div>

@{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }

SalesApp/Views/Sprint/Details.cshtml
@model SalesApp.Models.SprintViewModel

@{
    Layout = "_Layout";
}

@section Styles {
    <environment names="Development,Staging,Production">
        <link rel="stylesheet" href="~/css/table.items.min.css" />
    </environment>
}

<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>@ViewData["Title"]</h2>
        <ol class="breadcrumb">
            <li>
                <a href="@Url.Action("Index", "Home")">Home</a>
            </li>
            <li>
                <a href="@Url.Action("Index", "Sprint")">Sprints</a>
            </li>
            <li class="active">
                <strong>@ViewData["Title"]</strong>
            </li>
        </ol>
    </div>
    <div class="col-lg-2">

    </div>
</div>
<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox">
                <div class="ibox-content">
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="m-b-md">
                                <h2>@Model.Name</h2>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-5">
                            <dl class="dl-horizontal">

                                <dt>Strarts:</dt>
                                <dd>@(Model.From.HasValue ? Model.From.Value.ToString("D") : "")</dd>
                            </dl>
                        </div>
                        <div class="col-lg-7" id="cluster_info">
                            <dl class="dl-horizontal">
                                <dt>Finishs:</dt>
                                <dd>@(Model.From.HasValue ? Model.From.Value.ToString("D") : "")</dd>
                            </dl>
                        </div>
                    </div>
                    <div class="ibox float-e-margins">
                        <div class="ibox-content">
                            @Html.Partial("~/Views/Task/Partial/_DataTaskPartial.cshtml", Model.TaskModels)
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@Html.HiddenFor(m => m.SprintId, new { @id = "currSprintId" })

<div id="modal-form" class="modal fade" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-body" id="modalCreateEdit">

            </div>
        </div>
    </div>
</div> 

@section Scripts {
    <environment names="Development,Staging,Production">
        <script src="~/js/table.items.handler.min.js"></script>
    </environment>

    <environment names="Development">
        <script src="~/js/taskManager.js"></script>
    </environment>

    <environment names="Staging,Production">
        <script src="~/js/taskManager.min.js"></script>
    </environment>
}

SalesApp/Views/Sprint/Edit.cshtml
@using SalesApp.Models
@model SalesApp.Models.CreateEditSprintViewModel

<div class="row">
    <div class="col-sm-12 b-r">
        <h3 class="m-t-none m-b">@ViewData["Title"]</h3>

        <form asp-controller="Sprint" asp-action="Edit" data-ajax-begin="onBegin" data-ajax-complete="onComplete" data-ajax-failure="onFailure" data-ajax="true" data-ajax-success="onSuccessEdit" data-ajax-method="POST" id="modalSubmit" class="form-horizontal">
            @Html.Partial("Partial/_CreateEditSprintPartial", Model)
        </form>

    </div>
</div>

@{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }

<environment names="Development">
    <script src="~/lib/bootstrap-datepicker/dist/js/bootstrap-datepicker.js" asp-append-version="true"></script>
</environment>
<environment names="Staging,Production">
    <script src="~/lib/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js"></script>
</environment>

<script>
    $('#dateRange .input-daterange').datepicker({
        keyboardNavigation: false,
        forceParse: false,
        autoclose: true,
        format: "dd/mm/yyyy"
    });
</script>

SalesApp/Views/Sprint/Index.cshtml
@model System.Collections.Generic.List<SalesApp.Models.SprintViewModel>

@{
    Layout = "_Layout";
}

@section Styles {
    <environment names="Development,Staging,Production">
        <link rel="stylesheet" href="~/css/table.items.min.css" />
        
        <link rel="stylesheet" href="~/lib/bootstrap-datepicker/dist/css/bootstrap-datepicker3.min.css" />
    </environment>
}

<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>@ViewData["Title"]</h2>
        <ol class="breadcrumb">
            <li>
                <a href="@Url.Action("Home", "Index")">Home</a>
            </li>
            <li class="active">
                <strong>@ViewData["Title"]</strong>
            </li>
        </ol>
    </div>
    <div class="col-lg-2">

    </div>
</div>
<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>List of sprints</h5>
                    <div class="ibox-tools">
                        <a class="close-link">
                            <i class="fa fa-times"></i>
                        </a>
                    </div>
                </div>

                <div class="ibox-content">
                    <a data-toggle="modal" class="btn btn-primary" href="#modal-form" id="modalOpenForm">Create new sprint</a>
                    <table class="table table-striped table-bordered table-hover" id="tableSprint">
                        <thead>
                        <tr>
                            <th>Name</th>
                            <th>From</th>
                            <th>To</th>
                            <th>Action</th>
                        </tr>
                        </thead>
                        <tbody id="sprintTable">
                        @foreach (var item in Model)
                        {
                            <tr class="gradeX" id="sprint_@item.SprintId">
                                <td>@item.Name</td>
                                <td>@(item.From.HasValue? item.From.Value.ToString("D") : "")</td>
                                <td>@(item.To.HasValue ? item.To.Value.ToString("D") : "")</td>
                                <td>
                                    <div class="text-right footable-visible footable-last-column">
                                        <div class="btn-group">
                                            @Html.ActionLink("View", "Details", "Sprint", new { @id = item.SprintId }, new { @class = "btn-primary btn btn-xs" })
                                            <button class="btn-warning btn btn-xs edit-button" id="edit_sprint_@item.SprintId">Edit</button>
                                            <button class="btn-danger btn btn-xs delete-button" id="delete_sprint_@item.SprintId">Delete</button>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                        }
                        </tbody>
                        <tfoot>
                        <tr>
                            <th>Name</th>
                            <th>From</th>
                            <th>To</th>
                            <th>Action</th>
                        </tr>
                        </tfoot>
                    </table>

                </div>
            </div>
        </div>
    </div>
</div>

<div id="modal-form" class="modal fade" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-body" id="modalCreateEdit">
                
            </div>
        </div>
    </div>
</div>    

@section Scripts {

    <environment names="Development,Staging,Production">
        <script src="~/lib/slimScroll/jquery.slimscroll.min.js"></script>
        <script src="~/js/table.items.handler.min.js"></script>
    </environment>

    <environment names="Development">
        <script src="~/js/sprintManager.js"></script>
    </environment>

    <environment names="Staging,Production">
        <script src="~/js/sprintManager.min.js"></script>
    </environment>

}